gamewheel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('library/', include('library.urls')),
    path('accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

home/urls.py
from django.urls import path
from home import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('play/', views.PlayView.as_view(), name='play')
]

library/urls.py
from django.urls import path

from library import views

app_name = "library"
urlpatterns = [
    path("", views.ByPlayerView.as_view(), name="my_library"),
    path("profile/", views.MyProfileView.as_view(), name="my_profile"),
    path("import/", views.ImportLibraryView.as_view(), name="import_library"),
    path("error/groups/", views.NotInGroupsView.as_view(), name="not-in-groups"),
    path("<int:appid>/playing", views.MarkAsPlayingView.as_view(), name="mark_play"),
    path(
        "<int:appid>/finished", views.MarkAsFinishedView.as_view(), name="mark_finished"
    ),
]

library/models.py
from datetime import datetime
from enum import Enum

from allauth.socialaccount.models import SocialApp
from django.contrib.sites.models import Site
from django.db import models
from django.db.models import Count
from django.db.models import Max
from django.db.models import Min
from django_random_queryset import strategies
from steam.webapi import WebAPI


class PlayChoice(Enum):
    NONE = "unknown"
    PLAYING = "playing"
    FINISHED = "finished"


class RandomQuerySet(models.query.QuerySet):
    def random(self, amount=1):
        aggregates = self.aggregate(
            min_id=Min("appid"), max_id=Max("appid"), count=Count("appid")
        )

        if not aggregates["count"]:
            return self.none()

        if aggregates["count"] <= amount:
            return self.all()

        if (aggregates["max_id"] - aggregates["min_id"]) + 1 == aggregates["count"]:
            return self.filter(
                appid__in=strategies.min_max(
                    amount,
                    aggregates["min_id"],
                    aggregates["max_id"],
                    aggregates["count"],
                )
            )

        try:
            selected_ids = strategies.min_max_count(
                amount, aggregates["min_id"], aggregates["max_id"], aggregates["count"]
            )
        except strategies.SmallPopulationSize:
            selected_ids = self.values_list("appid", flat=True)

        assert len(selected_ids) > amount
        return self.filter(appid__in=selected_ids).order_by("?")[:amount]


class GameManager(models.Manager):
    def random(self, *args, **kwargs):
        return self.__get_queryset().random(*args, **kwargs)

    def get_queryset(self):
        return RandomQuerySet(self.model)


class Game(models.Model):

    # Custom manager to have a clean random selector
    objects = GameManager()

    appid = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255)

    icon_id = models.CharField(max_length=40)
    logo_id = models.CharField(max_length=40)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def owners(self):
        return self.player_set.count()

    def get_icon_url(self):
        return f"http://media.steampowered.com/steamcommunity/public/images/apps/{self.appid}/{self.icon_id}.jpg"

    def get_logo_url(self):
        return f"http://media.steampowered.com/steamcommunity/public/images/apps/{self.appid}/{self.logo_id}.jpg"

    def __str__(self):
        return f"{self.name}"

    class Meta:
        ordering = ("name",)


class PlayerManager(models.Manager):
    def import_library(self, player):
        steam_app = SocialApp.objects.filter(provider="steam").first()
        api = WebAPI(key=steam_app.secret)

        games = api.IPlayerService.GetOwnedGames(
            steamid=player.steamid,
            include_appinfo=True,
            include_played_free_games=True,
            appids_filter=None,
        )["response"]

        for game in games["games"]:
            game_obj, created = Game.objects.update_or_create(
                appid=game["appid"],
                defaults={
                    "name": game["name"],
                    "icon_id": game["img_icon_url"],
                    "logo_id": game["img_logo_url"],
                },
            )

            if created:
                print("Game %s created in DB" % game["name"])
            else:
                print("Game %s updated in DB" % game["name"])

            # User's stat on game
            GameStat.objects.update_or_create(
                player=player,
                game=game_obj,
                defaults={"playtime": game["playtime_forever"]},
            )


class Player(models.Model):
    objects = PlayerManager()
    steamid = models.BigIntegerField(primary_key=True)
    nickname = models.CharField(max_length=255)
    real_name = models.CharField(max_length=255)
    profile_url = models.URLField()

    avatar_url = models.URLField()
    avatar_m_url = models.URLField()
    avatar_f_url = models.URLField()

    games = models.ManyToManyField(Game, through="GameStat")

    country_code = models.CharField(max_length=4)

    creation_date = models.DateTimeField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nickname

    def get_currently_playing(self):
        return GameStat.objects.filter(player=self, status=PlayChoice.PLAYING)

    def get_finished(self):
        return GameStat.objects.filter(player=self, status=PlayChoice.FINISHED)

    class Meta:
        ordering = ("nickname",)


class GameStat(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    playtime = models.IntegerField(default=0)
    status = models.CharField(
        max_length=50,
        choices=[(state, state.value) for state in PlayChoice],
        default=PlayChoice.NONE,
    )

    started_at = models.DateTimeField(blank=True, null=True)
    finished_at = models.DateTimeField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def play(self):
        self.status = PlayChoice.PLAYING
        self.started_at = datetime.now()

        return self.save()

    def finish(self):
        self.status = PlayChoice.FINISHED
        self.finished_at = datetime.now()

        return self.save()


class Group(models.Model):
    group_id = models.BigIntegerField()
    name = models.CharField(max_length=255)
    headline = models.CharField(max_length=255, null=True)
    url = models.URLField()

    avatar_url = models.URLField()
    avatar_m_url = models.URLField()
    avatar_f_url = models.URLField()

    members = models.ManyToManyField(Player, related_name="groups")

    # Link to a Django site
    site = models.ForeignKey(Site, on_delete=models.CASCADE, related_name="groups")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

library/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView

from .models import Game
from .models import GameStat
from .models import Group
from .models import Player


class NotInGroupsView(TemplateView):
    template_name = "library/not_in_groups.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["groups"] = Group.objects.filter(
            site=get_current_site(self.request)
        ).all()

        return context


class ByPlayerView(ListView):
    model = Game
    context_object_name = "games"
    paginate_by = 12

    def get_queryset(self):
        player = self.request.user.get_player()
        return Game.objects.filter(player=player)


class MyProfileView(DetailView):
    model = Player
    context_object_name = "player"
    template_name = "library/my_profile.html"

    def get_object(self, queryset=None):
        return self.request.user.get_player()


class ImportLibraryView(RedirectView):
    permanent = False
    pattern_name = "library:my_profile"

    def get_redirect_url(self, *args, **kwargs):
        player = self.request.user.get_player()
        Player.objects.import_library(player)
        return super().get_redirect_url(*args, **kwargs)


class MarkAsPlayingView(RedirectView):
    permanent = False
    query_string = False
    pattern_name = "library:my_profile"

    def get_redirect_url(self, *args, **kwargs):
        game = get_object_or_404(
            GameStat, player=self.request.user.get_player(), game_id=kwargs["appid"]
        )
        game.play()
        return super().get_redirect_url()


class MarkAsFinishedView(RedirectView):
    permanent = False
    query_string = False
    pattern_name = "library:my_profile"

    def get_redirect_url(self, *args, **kwargs):
        game = get_object_or_404(
            GameStat, player=self.request.user.get_player(), game_id=kwargs["appid"]
        )
        game.finish()
        return super().get_redirect_url()

library/templates/library/_gamecard.html
<article class="media">
  <figure class="media-left">
    <p class="image is-16by9">
      <img src="{{ game.get_logo_url }}">
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong>{{game.name}}</strong> <small></small>
        <br>
        {{game.owners.count}} players owning it
      </p>
    </div>
      {%  if not simple %}
    <nav class="level is-mobile">
      <div class="level-left">
        <a class="level-item" href="{% url 'library:mark_play' appid=game.appid %}">
          <span class="icon is-small"><i class="fas fa-retweet"></i></span>
        </a>
        <a class="level-item" href="{% url 'library:mark_finished' appid=game.appid %}">
          <span class="icon is-small"><i class="fas fa-heart"></i></span>
        </a>
      </div>
    </nav>
      {% endif %}
  </div>
</article>

library/templates/library/game_list.html
{% extends 'layout.html' %}
{% block content %}
    <div class="section container">
        <div class="columns is-multiline">
            {% for game in games %}
                <div class="column is-half">{% include 'library/_gamecard.html' with game=game %}</div>
            {% endfor %}
        </div>

    {% if is_paginated %}
        {% include '_pagination.html' with page=page_obj paginator=paginator only %}
    {% endif %}
    </div>
{% endblock content %}

library/templates/library/my_profile.html
{% extends 'layout.html' %}
{% block content %}
    {% if player.games.count == 0 %}
    <section class="container">
    <div class="notification is-warning">
        <strong>Warning!</strong> Your library is empty. Please make sure your Steam profile is public
        then click <a href="{% url 'library:import_library' %}">here</a> to import your library.
</div>
    </section>
    {% endif %}
<section class="hero">
    <div class="hero-body">
        <div class="container">
            <img src="{{ player.avatar_f_url }}" class="is-pulled-right"/>
            <h1 class="title">{{player.nickname}}</h1>
            <h2 class="subtitle">
                SteamID: {{ player.steamid }}
            </h2>
        </div>
    </div>
</section>
<section class="section">
    <article class="container" id="game-stats">
        <nav class="level">
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Owned games</p>
                    <p class="title">{{player.games.count}}</p>
                </div>
            </div>
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Playing games</p>
                    <p class="title">{{player.get_currently_playing.count}}</p>
                </div>
            </div>
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Finished games</p>
                    <p class="title">{{player.get_finished.count}}</p>
                </div>
            </div>
        </nav>
    </article>
</section>
<section class="section">
    <article class="container">
        <div class="columns">
            <div class="column is-half">
                <h2 class="title is-3">My play-list</h2>
                {% for play in player.get_currently_playing.all %}
                    {% include 'library/_gamecard.html' with game=play.game simple=True only %}
                {% endfor %}
            </div>
            <div class="column is-half">
                <h2 class="title is-3">My friends</h2>
                <p>To be developed</p>
            </div>
        </div>
    </article>
</section>
{% endblock content %}

library/templates/library/not_in_groups.html
{% extends 'layout.html' %}
{% load i18n %}
{% block head_title %}{% trans "Access denied" %}{% endblock %}
{% block content %}
    <section class="container section">
        <article>
            <h1 class="title is-2">{% trans "Access denied" %}</h1>
            <p>Please make sure you belongs to the following groups on Steam:</p>
            <ul>
            {% for group in groups %}
                <li><a href="{{ group.url }}">{{ group.name }}</a></li>
            {% endfor %}
            </ul>
        </article>
    </section>
{% endblock content %}