gamewheel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('library/', include('library.urls')),
    path('accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

home/urls.py
from django.urls import path
from home import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('play/', views.PlayView.as_view(), name='play')
]

library/urls.py
from django.urls import path

from library import views

app_name = "library"
urlpatterns = [
    path("", views.ByPlayerView.as_view(), name="my_library"),
    path("profile/", views.MyProfileView.as_view(), name="my_profile"),
    path("import/", views.ImportLibraryView.as_view(), name="import_library"),
    path("error/groups/", views.NotInGroupsView.as_view(), name="not-in-groups"),
    path("<int:appid>/playing", views.MarkAsPlayingView.as_view(), name="mark_play"),
    path(
        "<int:appid>/finished", views.MarkAsFinishedView.as_view(), name="mark_finished"
    ),
]

templates/_messages.html
<section class="section container">
    {% for message in messages %}
    <div class="notification is-primary">
  <button class="delete"></button>
  {{ message }}
</div>
{% endfor %}
</section>

templates/_navbar.html
{% load socialaccount %}
<nav class="navbar" role="navigation" aria-label="Primary navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'home:index' %}">
            GameWheel
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbar-top" class="navbar-menu">
    {%  if user.is_authenticated %}
        <div class="navbar-start">
            <a class="navbar-item" href="{% url 'home:play' %}">
                Play a game
            </a>


        </div>
    {% endif %}

    <div class="navbar-end">
    {% if user.is_authenticated %}
        <a class="navbar-item" href="{% url 'library:my_library' %}">My library</a>
        <a class="navbar-item" href="{% url 'library:my_profile' %}">My profile</a>
    {% endif %}
        <div class="navbar-item">
            <div class="buttons">
            {%  if user.is_authenticated %}
                <a class="button is-light" href="{% url 'account_logout' %}?next=/">Logout</a>
            {% else %}
                <a class="button is-primary" href="{% provider_login_url 'steam' %}">
                    <span class="icon is-large">
                        <i class="fab fa-steam"></i>
                    </span>
                    <strong>Sign up with Steam</strong>
                </a>
            {% endif %}
            </div>
        </div>
    </div>
</div>
</nav>

templates/_pagination.html
<nav class="pagination is-centered" role="navigation" aria-label="pagination">
    {% if page.has_previous %}
        <a class="pagination-previous" href="?page={{ page.previous_page_number }}">Previous</a>
    {% else %}
        <a class="pagination-previous" disabled>Previous</a>
    {% endif %}
    {% if page.has_next %}
        <a class="pagination-next" href="?page={{ page.next_page_number }}">Next page</a>
    {% else %}
        <a class="pagination-next" disabled>Next page</a>
    {% endif %}

    <ul class="pagination-list">
        {% if page.number > 1 %}
            <li><a class="pagination-link" aria-label="Goto page 1" href="?page=1">1</a></li>
            {% if page.number > 3 %}<li><span class="pagination-ellipsis">&hellip;</span></li>{% endif%}
            {% if page.number > 2 %}
                <li><a class="pagination-link" href="?page={{ page.number|add:"-1" }}" aria-label="Goto page {{ page.number|add:"-1" }}">{{ page.number|add:"-1" }}</a></li>
            {% endif %}
        {% endif %}
        <li><a class="pagination-link is-current" aria-label="Page {{ page.number }}" aria-current="page">{{ page.number }}</a></li>

        {% if page.number < paginator.num_pages %}
            {% if page.number|add:1 < paginator.num_pages %}
                <li><a class="pagination-link" href="?page={{ page.number|add:1 }}" aria-label="Goto page {{ page.number|add:1 }}">{{ page.number|add:1 }}</a></li>
            {% endif %}
            {% if page.number|add:2 < paginator.num_pages %}<li><span class="pagination-ellipsis">&hellip;</span></li>{% endif %}
        <li><a class="pagination-link" aria-label="Goto page 86" href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
        {% endif %}
    </ul>
</nav>

templates/layout.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>GameWheel - {% block head_title %}What will you play next ?{% endblock %}</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    {% render_bundle 'main' 'css'%}
    {% block extra_head %}{% endblock %}
</head>
<body>
    <header>
        {% include '_navbar.html' %}
    </header>
    {% if messages %}
        {% include '_messages.html' %}
    {% endif %}
    {% block content %}{% endblock content %}
    {% block extra_content %}{% endblock %}
{% render_bundle 'main'%}
</body>
</html>